#   An Introduction to NumPy  ![title](numpy_logo.png)

***

All exercises here are based on python courses on www.datacamp.com unless stated otherwise

Adds support for large, multi-dimensional arrays and matrices, it includes high-level math functions to use with these arrays.

NumPy has a comparable functionality to that of MATLAB. They are both interpreted, and both allow for fast program writing as long as most operations work on arrays or matrices and not on scalars. 

MATLAB has a large number of toolboxes, Simulink in particular. In contrast, NumPy is highly integrated with Python, which is a more complete and much more modern programming language. Other Python packages add complimentary functionality to NumPy that make Python to be even more MATLAB like. SciPy and Matplotlib are good examples of this.

The NumPy package is included with Anaconda

I like football and found several datasets around that, I chose the data set for EA FIFA 2017 player's. You can download this data set at: https://www.kaggle.com/artimous/complete-fifa-2017-player-dataset-global#FullData.csv

In [18]:
#we'll use the pandas package as well, basically to import files in this exercises, we'll talk about that at a later time
import pandas as pd
df = pd.read_csv("data/FullData2.csv",sep=",")
df

,Name,Nationality,National_Position,National_Kit,Club,Club_Position,Club_Kit,Club_Joining,Contract_Expiry,Rating,...,Long_Shots,Curve,Freekick_Accuracy,Penalties,Volleys,GK_Positioning,GK_Diving,GK_Kicking,GK_Handling,GK_Reflexes
0,Cristiano Ronaldo,Portugal,LS,7.0,Real Madrid,LW,7.0,07/01/2009,2021.0,94,...,90,81,76,85,88,14,7,15,11,11
1,Lionel Messi,Argentina,RW,10.0,FC Barcelona,RW,10.0,07/01/2004,2018.0,93,...,88,89,90,74,85,14,6,15,11,8
2,Neymar,Brazil,LW,10.0,FC Barcelona,LW,11.0,07/01/2013,2021.0,92,...,77,79,84,81,83,15,9,15,9,11
3,Luis Suárez,Uruguay,LS,9.0,FC Barcelona,ST,9.0,07/11/2014,2021.0,92,...,86,86,84,85,88,33,27,31,25,37
4,Manuel Neuer,Germany,GK,1.0,FC Bayern,GK,1.0,07/01/2011,2021.0,92,...,16,14,11,47,11,91,89,95,90,89
5,De Gea,Spain,GK,1.0,Manchester Utd,GK,1.0,07/01/2011,2019.0,90,...,12,21,19,40,13,86,88,87,85,90
6,Robert Lewandowski,Poland,LS,9.0,FC Bayern,ST,9.0,07/01/2014,2021.0,90,...,82,77,76,81,86,8,15,12,6,10
7,Gareth Bale,Wales,RS,11.0,Real Madrid,RW,11.0,09/02/2013,2022.0,90,...,90,86,85,76,76,5,15,11,15,6
8,Zlatan Ibrahimović,Sweden,NaN,NaN,Manchester Utd,ST,9.0,07/01/2016,2017.0,90,...,88,82,82,91,93,9,13,10,15,12
9,Thibaut Courtois,Belgium,GK,1.0,Chelsea,GK,13.0,07/26/2011,2019.0,89,...,17,19,11,27,12,86,84,69,91,89
10,Jérôme Boateng,Germany,RCB,17.0,FC Bayern,Sub,17.0,07/14/2011,2021.0,89,...,58,56,31,46,53,6,7,15,12,5
11,Eden Hazard,Belgium,LF,10.0,Chelsea,LW,10.0,07/01/2012,2020.0,89,...,82,82,79,86,79,8,11,6,12,8
12,Luka Modrić,Croatia,NaN,NaN,Real Madrid,RCM,19.0,08/01/2012,2020.0,89,...,82,79,77,80,74,14,13,7,9,9
13,Mesut Özil,Germany,CAM,10.0,Arsenal,CAM,11.0,09/02/2013,2018.0,89,...,76,84,79,67,77,6,6,10,14,14
14,Gonzalo Higuaín,Argentina,Sub,9.0,Juventus,ST,9.0,07/26/2016,2021.0,89,...,80,74,62,70,88,5,5,7,12,10
15,Thiago Silva,Brazil,Sub,14.0,PSG,LCB,2.0,07/01/2012,2020.0,89,...,71,61,73,71,63,9,9,5,12,10
16,Sergio Ramos,Spain,LCB,15.0,Real Madrid,LCB,4.0,08/01/2005,2020.0,89,...,55,73,67,68,66,7,11,9,8,11
17,Sergio Agüero,Argentina,Sub,7.0,Manchester City,ST,10.0,07/28/2011,2020.0,89,...,84,82,72,80,85,11,13,6,15,14
18,Paul Pogba,France,NaN,NaN,Manchester Utd,LCM,6.0,08/09/2016,2021.0,88,...,88,82,82,76,84,4,5,2,6,3
19,Antoine Griezmann,France,CAM,7.0,Atlético Madrid,RS,7.0,07/29/2014,2021.0,88,...,82,84,75,71,87,13,14,14,8,14
20,Kevin De Bruyne,Belgium,RCM,7.0,Manchester City,RCM,17.0,08/30/2015,2021.0,88,...,86,81,84,77,82,10,15,5,13,13
21,Marco Reus,Germany,NaN,NaN,Bor. Dortmund,LW,11.0,07/01/2012,2019.0,88,...,85,90,84,84,88,13,12,13,12,11
22,Alexis Sánchez,Chile,LW,7.0,Arsenal,ST,7.0,07/10/2014,2018.0,88,...,81,78,78,77,83,12,10,15,10,13
23,Toni Kroos,Germany,LDM,8.0,Real Madrid,LCM,8.0,07/17/2014,2022.0,88,...,88,85,84,73,82,7,10,13,11,10
24,Diego Godín,Uruguay,LCB,3.0,Atlético Madrid,LCB,2.0,08/01/2010,2019.0,88,...,43,49,51,50,47,5,6,15,8,15
25,Mats Hummels,Germany,LCB,5.0,FC Bayern,LCB,5.0,07/01/2016,2021.0,88,...,51,65,53,68,60,5,15,10,6,6
26,Hugo Lloris,France,GK,1.0,Spurs,GK,1.0,08/01/2012,2022.0,88,...,14,11,10,40,11,82,87,68,87,90
27,Giorgio Chiellini,Italy,LCB,3.0,Juventus,LCB,3.0,07/01/2005,2018.0,88,...,49,60,31,50,45,4,3,2,3,3
28,Philipp Lahm,Germany,NaN,NaN,FC Bayern,RB,21.0,11/01/2002,2018.0,88,...,65,77,59,69,66,14,11,5,12,5
29,Pepe,Portugal,RCB,3.0,Real Madrid,RCB,3.0,07/01/2007,2017.0,88,...,56,44,47,57,23,9,8,5,15,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17558,Kieran Butler,Republic of Ireland,NaN,NaN,Bray Wanderers,Res,30.0,04/25/2016,2017.0,47,...,23,26,25,35,24,12,12,12,8,6
17559,Kyle Egan,England,NaN,NaN,Exeter City,Res,36.0,12/10/2015,2017.0,47,...,23,28,28,35,23,9,7,10,8,8
17560,Alfie Kilgour,England,NaN,NaN,Bristol Rovers,Res,32.0,10/13/2015,2020.0,47,...,28,33,24,35,19,10,6,11,11,5
17561,Shane Hanney,Republic of Ireland,NaN,NaN,Shamrock Rovers,Sub,2.0,02/01/2015,2017.0,47,...,43,39,41,44,35,13,14,12,5,14
17562,Louis Jones,England,NaN,NaN,Doncaster,Sub,33.0,03/06/2016,2017.0,47,...,14,12,13,48,15,45,45,43,43,48
17563,Ben Kelly,Republic of Ireland,NaN,NaN,Dundalk,Sub,30.0,02/24/2017,2023.0,47,...,12,18,17,13,15,46,48,50,46,44
17564,Kaylen Hinds,England,NaN,NaN,Stevenage,Res,26.0,02/04/2015,2019.0,47,...,47,37,26,62,36,9,15,13,11,6
17565,James King,England,NaN,NaN,Bradford City,Res,21.0,09/16/2014,2023.0,47,...,18,26,16,32,22,10,6,7,15,12
17566,Neil McLaughlin,Scotland,NaN,NaN,Partick Thistle,Sub,26.0,05/26/2015,2017.0,47,...,30,34,30,39,41,14,8,15,16,9
17567,Nathan Clifford,Republic of Ireland,NaN,NaN,Finn Harps,Res,33.0,08/01/2015,2017.0,46,...,22,33,28,20,19,13,12,8,11,5
17568,Ciaran Kelly,Republic of Ireland,NaN,NaN,Finn Harps,Sub,35.0,08/01/2015,2017.0,46,...,17,29,25,28,17,7,7,9,14,15
17569,Adam Kelsey,England,NaN,NaN,Scunthorpe Utd,Res,41.0,01/26/2017,2019.0,46,...,7,13,12,17,6,43,46,54,47,48
17570,Dominic Peppard,Republic of Ireland,NaN,NaN,Bohemian FC,Sub,22.0,12/01/2016,2017.0,46,...,16,28,20,31,28,5,13,5,15,13
17571,Gavin Dowling,Republic of Ireland,NaN,NaN,Wexford Youths,Sub,23.0,08/01/2015,2020.0,46,...,11,13,10,12,12,43,45,57,44,46
17572,Tommy Käßemodel,Germany,NaN,NaN,Erzgebirge Aue,Res,29.0,07/01/2016,2017.0,46,...,39,52,37,41,34,13,10,6,12,6
17573,Ronan Wilson,Northern Ireland,NaN,NaN,Derry City,Sub,35.0,01/01/2016,2017.0,46,...,33,23,21,36,22,11,11,11,8,10
17574,Darragh Doherty,Republic of Ireland,NaN,NaN,Longford Town,Sub,26.0,01/01/2016,2020.0,46,...,32,32,33,40,26,9,7,14,10,10
17575,Myles Judd,England,NaN,NaN,Leyton Orient,Sub,29.0,09/01/2015,2017.0,46,...,22,27,29,33,21,12,5,14,5,10
17576,Sam Hornby,England,NaN,NaN,Burton Albion,Res,31.0,05/05/2015,2017.0,46,...,18,19,13,14,12,41,50,44,42,48
17577,Sam Sargeant,England,NaN,NaN,Leyton Orient,Sub,24.0,09/01/2014,2018.0,46,...,13,16,13,24,16,47,48,43,42,51
17578,Steven Alzate,England,NaN,NaN,Leyton Orient,Res,31.0,09/21/2016,2017.0,45,...,29,40,22,35,30,7,9,6,6,6
17579,Sam Dalby,England,NaN,NaN,Leyton Orient,Sub,30.0,08/30/2016,2019.0,45,...,44,34,23,40,35,12,7,14,12,7
17580,Henry Ochieng,England,NaN,NaN,Leyton Orient,Sub,32.0,12/02/2016,2019.0,45,...,36,32,31,36,25,7,12,12,13,9
17581,Harry Clifton,England,NaN,NaN,Grimsby Town,Res,15.0,06/30/2015,2017.0,45,...,35,32,27,24,27,7,9,8,6,10
17582,Mark McElhinney,Republic of Ireland,NaN,NaN,Derry City,Res,20.0,01/01/2016,2017.0,45,...,12,11,11,16,12,46,41,50,45,44
17583,Adam Dunbar,Republic of Ireland,NaN,NaN,Wexford Youths,Sub,30.0,02/01/2016,2020.0,45,...,13,11,13,15,12,39,44,52,41,46
17584,Dylan McGoey,Republic of Ireland,NaN,NaN,Longford Town,Sub,28.0,01/01/2016,2020.0,45,...,11,12,13,16,12,47,39,46,46,46
17585,Tommy Ouldridge,England,NaN,NaN,Swindon Town,Res,32.0,03/03/2015,2023.0,45,...,42,35,36,42,37,15,7,13,14,7
17586,Mark Foden,Scotland,NaN,NaN,Ross County,Sub,45.0,03/02/2016,2017.0,45,...,12,13,12,24,12,40,45,44,43,45
17587,Barry Richardson,England,NaN,NaN,Wycombe,Sub,13.0,01/30/2014,2023.0,45,...,16,12,11,22,12,58,37,37,51,33

That's not a convenient way to see this, I just want to see the first few lines.

In [46]:
print(df.head())

                Name Nationality National_Position  National_Kit  \
0  Cristiano Ronaldo    Portugal                LS           7.0
1       Lionel Messi   Argentina                RW          10.0
2             Neymar      Brazil                LW          10.0
3        Luis Suárez     Uruguay                LS           9.0
4       Manuel Neuer     Germany                GK           1.0

           Club Club_Position  Club_Kit Club_Joining  Contract_Expiry  Rating  \
0   Real Madrid            LW       7.0   07/01/2009           2021.0      94
1  FC Barcelona            RW      10.0   07/01/2004           2018.0      93
2  FC Barcelona            LW      11.0   07/01/2013           2021.0      92
3  FC Barcelona            ST       9.0   07/11/2014           2021.0      92
4     FC Bayern            GK       1.0   07/01/2011           2021.0      92

      ...      Long_Shots Curve Freekick_Accuracy Penalties  Volleys  \
0     ...              90    81                76        85       88
1     ...              88    89                90        74       85
2     ...              77    79                84        81       83
3     ...              86    86                84        85       88
4     ...              16    14                11        47       11

  GK_Positioning GK_Diving  GK_Kicking  GK_Handling  GK_Reflexes
0             14         7          15           11           11
1             14         6          15           11            8
2             15         9          15            9           11
3             33        27          31           25           37
4             91        89          95           90           89

[5 rows x 53 columns]

To make things easier, for the time being I filtered out Height and Weight and saved them as different files. We're going to import those instead. So no we import NumPy as np to save some writing

In [9]:
import numpy as np
Height = pd.read_csv("data/Height.csv",sep=",")
np_H = np.array(Height)
np_H

array([[185],
       [170],
       [174],
       ...,
       [173],
       [180],
       [185]], dtype=int64)

note: Once we entered data, got a variable, or imported a package into our notebook, we don't need to do that again.

In [10]:
Weight = pd.read_csv("data/Weight.csv",sep=",")
np_W = np.array(Weight)
np_W

array([[80],
       [72],
       [68],
       ...,
       [61],
       [80],
       [77]], dtype=int64)

I want to know the player's BMI. Lets try out what happens if we do it without NumPy   * BMI = W/(H^2)

In [11]:
Weight = pd.read_csv("data/Weight.csv",sep=",")
Height = pd.read_csv("data/Height.csv",sep=",")
bmi = Weight / (Height ** 2)
print(bmi.head())

   Height  Weight
0     NaN     NaN
1     NaN     NaN
2     NaN     NaN
3     NaN     NaN
4     NaN     NaN

NumPy to the rescue

In [19]:
Weight = pd.read_csv("data/Weight.csv",sep=",")
#We now create a NumPy array
np_W = np.array(Weight)
Height = pd.read_csv("data/Height.csv",sep=",")
np_H = np.array(Height)
bmi = np_W / (np_H/100) ** 2
bmi

array([[23.37472608],
       [24.91349481],
       [22.46003435],
       ...,
       [20.38156971],
       [24.69135802],
       [22.49817385]])

NumPy works, because it assumes that your NumPy array has values that are all of the same type (floats, booleans, etc).
if you enter an array:

In [14]:
array = np.array([10, "Pele", True])
array

array(['10', 'Pele', 'True'], dtype='<U11')

Everything was converted to strings

A NumPy array is a another is another kind of Python Type, like floats, and booleans, so it comes with its own Methods (and each method has a particular behavior)

In [15]:
normal_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])
#without NumPy
nl=normal_list + normal_list
print(nl)
#with NumPy
na=numpy_array + numpy_array
print(na)

[1, 2, 3, 1, 2, 3]
[2 4 6]

## NumPy Subsetting

If you want to get an element from your array, you can use square brackets (Rember, numbering starts at 0, not at 1)

Speciffically for NumPy you can also use an array for booleans to do subsetting for example, if you wanted to get all BMI values, in our previous exercise, for BMI values that are above 22.5. you could use

In [16]:
Weight = pd.read_csv("data/Weight.csv",sep=",")
np_W = np.array(Weight)
Height = pd.read_csv("data/Height.csv",sep=",")
np_H = np.array(Height)
bmi = np_W / (np_H/100) ** 2
bmi > 22.5

array([[ True],
       [ True],
       [False],
       ...,
       [False],
       [ True],
       [False]])

You could then use this boolean array inside square brackets to subset. only those lements that are above 22.5 will be selected

In [13]:
bmi[bmi>22.5]

array([23.37472608, 24.91349481, 25.66115203, ..., 24.48565201,
       23.37472608, 24.69135802])

This simple method is a great way to pre-process or get insights from your data!

# Operations with Arrays

We are now going to create a list of heights in centimeters, put that list in a NumPy Array and print the type of data

In [17]:
Heights_in_Cm = [180, 210, 175, 165, 180, 182, 205, 190]
np_Heights_in_Cm = np.array(Heights_in_Cm)
print(type(np_Heights_in_Cm))

<class 'numpy.ndarray'>

After a quick search on the internet, your TA found the Complete FIFA 2017 Player dataset. https://www.kaggle.com/artimous/complete-fifa-2017-player-dataset-global#FullData.csv
For class purposes we're only going to deal with player's heights at the moment, and we'll use Pandas to read that file, but we'll come back to that in the future, so don't pay much attention to the first 2 lines

1) We'll create a NumPy array with the Height data
3) We'll print that out
4) We'll convert that to inches, because... inches make so much sense, (said no one ever). and we're doing it for (data) science
5) We'll print that again

In [31]:
Height = pd.read_csv("data/Height.csv",sep=",")
np_height = np.array(Height)
print(np_height)

[[185]
 [170]
 [174]
 ...
 [173]
 [180]
 [185]]

let's convert it..

In [26]:
np_height_in = 0.393701*np_height
print(np_height_in)

[[72.834685]
 [66.92917 ]
 [68.503974]
 ...
 [68.110273]
 [70.86618 ]
 [72.834685]]

Just to check, what kind of data is this?

In [20]:
print(type(np_height))

<class 'numpy.ndarray'>

So, it's not boolean, string, or float... it's a numpy array

From our Intro, let's calculate BMI again

In [5]:
Weight = pd.read_csv("data/Weight.csv",sep=",")
np_weight = np.array(Weight)
bmi = np_weight / (np_height/100) ** 2
bmi

array([[23.37472608],
       [24.91349481],
       [22.46003435],
       ...,
       [20.38156971],
       [24.69135802],
       [22.49817385]])

So let's find the skinny players, say those with a BMI under 21

In [6]:
light = bmi < 21
print (light)
print(bmi[light])

[[False]
 [False]
 [False]
 ...
 [ True]
 [False]
 [False]]
[20.75638717 20.97117202 20.9839876  ... 20.74755019 20.91070816
 20.38156971]

## Coercion

As mentioned earlier, NumPy assumes all data elements within a NumPy array are of the same type, so when it finds something that is not, it forces it (coerces) it into a certain value. So remember Python lists and NumPy arrays can behave in different ways

In [32]:
a = np.array([1, 2, True])
print(a)
b = np.array([1, 2, False])
print(b)

[1 2 1]
[1 2 0]

### Subsetting

You can subset within NumPy just the same way you would in "normal" Python, by using square brackets. the first record is 0, and the last one is non-inclusive. let's use those BMI's again and print out whats at index 10.. then lets print out index 9 up to 15 inclusive

In [35]:
print(np_weight[10])
print("And index 10 to 15")
print(np_weight[9:16])

[90]
And index 10 to 15
[[91]
 [90]
 [74]
 [65]
 [76]
 [92]
 [79]]

# 2D - Numpy Arrays

So we've worked with the arrays "np_heights" and "np_weights" which were both 1 dimensional arrays, but it's perfectly possible to have 2D, 3D and all the way to 7-Dimensional arrays. We'll now work with 2D arrays

Let's make up a small list of lists, and import NumPy

In [42]:
Futbol = [[175, 77],[212, 103], [205, 99], [188, 79]]
np_Futbol = np.array(Futbol)
np_Futbol

array([[175,  77],
       [212, 103],
       [205,  99],
       [188,  79]])

np_Futbol is a rectangular data structure, each sublist corresponds to a row in the 2Dimensional numpy array. In fact just to make sure, if we call the shape attribute of the np_Futbol array that gives information on how the data structure looks like

In [39]:
np_Futbol.shape

(4, 2)

We can see that we have 4 rows and 2 columns

As mentioned before, an array can only contain one single type. if we change one float to a string, all of the other will be coerced to string, so it has only a single type.

In [40]:
Futbol = [[175, 77],[212, 103], [205, "99"], [188, 79]]
np_Futbol = np.array(Futbol)
np_Futbol

array([['175', '77'],
       ['212', '103'],
       ['205', '99'],
       ['188', '79']], dtype='<U11')

We conveniently have or Weight and Heights of our Football heroes in one nice table, again ignore those 2 initial lines, we're going to import numpy, create a 2D NumPy array and print out the shape

In [43]:
Football = pd.read_csv("data/FullData5.csv",sep=",")
np_Football = np.array(Football)
np_Football.shape

(17588, 3)

Woow, that's a lot of lines... and just 3 columns

In [44]:
print(Football.head())

                Name  Height  Weight
0  Cristiano Ronaldo     185      80
1       Lionel Messi     170      72
2             Neymar     174      68
3        Luis Suárez     182      85
4       Manuel Neuer     193      92

Subsetting is one of those areas were NumPy really shines. If you had a normal Python list subsetting can get complicated, but in NumPy it's quite intuitive. a ":" is used for slicing. If we did an operation with the whole line, our array would be recognized as a string.. Let's print the 50th row of our np_Football array:

In [45]:
print(np_Football[49, :])

['Sergio Busquets' 189 76]

He plays with Spain, they got a Russian surprise... haha Spasiba.

Anyways, let's continue doing some subsetting and select only the entire third column

In [46]:
np_weight = np_Football[:,2]
print(np_weight)

[80 72 68 ... 61 80 77]

Now, we'll find out how tall our 100th player is

In [47]:
print(np_Football[99,1])

181

Let's combine what we learned. We're going to subset or data so we can perform and arithmetic operation; which is to convert all measurements into imperial system just because we can, but we'll have to subset the 2nd & 3rd column, because the 1st is a string

In [48]:
HW=np_Football[:,1:]
conversion = np.array([0.393701, 2.20462])
print(HW*conversion)

[[72.83468500000001 176.3696]
 [66.92917 158.73263999999998]
 [68.503974 149.91415999999998]
 ...
 [68.110273 134.48182]
 [70.86618 176.3696]
 [72.83468500000001 169.75573999999997]]

Ta-daaaa

***

![title](img/stats-are-coming.jpeg)

don't worry... they're very simple

# Basic Stats

Looking at this basic stats out from the very beginning is good practice.. if you find that you have an average of 3 Mts tall players.... something is wrong with your data

Mean

In [54]:
mean=np.mean(HW[:,0])
mean

181.10546963838982

That's a lot of decimals, and it's very hard to know what that figure is just by the output. Let's make this figure more readable

In [55]:
print("Average " + str(round(mean,2)))

Average 181.11

Median

In [50]:
np.median(HW[:,1])

75.0

Std Dev

In [51]:
np.std(HW[:,0])

6.6749702781060405

Sum

In [52]:
np.sum(HW[:,0])

3185283

Sort

In [53]:
np.sort(HW[:,1])

array([48, 49, 50, ..., 107, 110, 110], dtype=object)